#!/usr/bin/env bash

set -Eeuo pipefail

DOCS=../react-compinators-docs

pnpm build:vite
pnpm build:docs
pnpm build:storybook
cp -r storybook-static/* "$DOCS"
cp -r docs "$DOCS"
cp docs/dev-tools-display-name-default.png "$DOCS/docs"
cp docs/dev-tools-display-name-custom.png "$DOCS/docs"
mkdir -p "$DOCS/src/storybook/css"
cp src/storybook/css/index.css "$DOCS/src/storybook/css"


